name: Endor Labs Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      id-token: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Endor Labs Scan
      uses: endorlabs/github-action@v1
      with:
        namespace: "endor-solutions-ypulse.github-ci"
        scan_dependencies: true
        scan_secrets: false
        enable_pr_comments: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        additional_args: "--use-bazel --use-bazel-aspects --bazel-targets-query='kind("go_binary|go_library|go_test|java_binary|java_library|js_binary|js_library|py_binary|py_library|py_test|ts_project", //projects/...)'"
        sarif_file: findings.sarif
    - name: Upload SARIF
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        sarif_file: findings.sarif
